name: Build & Release Module

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package KernelSU Module ZIP
        run: |
          bash build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uclamp_auto_profiler
          path: uclamp_auto_profiler.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: uclamp_auto_profiler.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
